site_name: nicewoo
site_description: NLP 유틸리티 (불용어 제거, 키워드 추출, 요약, 언어 감지)
site_author: 우성현
repo_url: https://github.com/WooMongGae/nicewoo
theme:
  name: material

nav:
  - Home: index.md
  - Functions:
      - Remove Stopwords: remove_stopwords.md
      - Extract Keywords: extract_keywords.md
      - Summarize: summarize.md
      - Detect Language: detect_language.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
